name: vsr
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=1.4.0=pyhd8ed1ab_0
  - accelerate=0.20.3=pyhd8ed1ab_0
  - aiohttp=3.8.4=py38h01eb140_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_3
  - asciitree=0.3.3=py_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.0.9=py38hfa26641_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=41.0.1=py38hcdda232_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py38h8dc9893_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - einops=0.6.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.12.2=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.3.3=py38h0a891b7_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py38h793c122_1
  - gnutls=3.6.13=h85f3911_1
  - grpcio=1.56.0=py38h94a1851_2
  - huggingface_hub=0.16.2=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.7.0=pyha770c72_0
  - importlib_metadata=6.7.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.24.0=pyh71e2992_0
  - ipython=8.12.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.1=py38h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py38h578d9bd_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_highlight_selected_word=0.2.0=py38h578d9bd_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - kornia=0.6.12=pyhd8ed1ab_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=13.1.0=he5830b7_0
  - libgrpc=1.56.0=h3905398_2
  - libhwloc=2.9.1=nocuda_h7313eea_6
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.23.3=hd1fb520_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.11.4=h0d562d8_0
  - libxslt=1.1.37=h0054252_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - lxml=4.9.3=py38h0ef1326_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.3=py38h01eb140_0
  - matplotlib-base=3.6.2=py38h945d387_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.0=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py38hfbd4bf9_0
  - multidict=6.0.4=py38h1de0b5d_0
  - munkres=1.1.4=py_0
  - nb_conda_kernels=2.3.1=py38h578d9bd_2
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.6.0=pyhd8ed1ab_0
  - nbconvert-core=7.6.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numcodecs=0.11.0=py38h8dc9893_1
  - numpy=1.24.4=py38h59b608b_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_0
  - pandoc=3.1.3=h32600fe_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py38hde6dc18_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py38h1de0b5d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=py38h06a4308_0
  - pyrsistent=0.19.3=py38h1de0b5d_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.17=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytz=2022.7=py38h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_5
  - pyzmq=25.1.0=py38h509eb50_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rsa=4.9=pyhd8ed1ab_0
  - safetensors=0.3.1=py38h0cc4f7c_0
  - seaborn=0.12.2=py38h06a4308_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.9.0=hf52228f_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h3d167d9_0
  - terminado=0.17.1=pyh41d4057_0
  - timm=0.9.2=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu118
  - tornado=6.3.2=py38h01eb140_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xarray=2022.11.0=py38h06a4308_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py38h01eb140_0
  - zarr=2.15.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - appdirs==1.4.4
    - cachetools==5.3.1
    - cftime==1.6.2
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - ema-pytorch
    - flow-vis==0.1
    - gcsfs
    - google-auth
    - google-cloud-storage
    - gitdb==4.0.10
    - gitpython==3.1.31
    - hjson==3.1.0
    - imageio==2.31.1
    - imageio-ffmpeg==0.4.8
    - moviepy==1.0.3
    - ninja==1.11.1
    - pathtools==0.1.2
    - piq==0.8.0
    - proglog==0.1.10
    - protobuf==4.23.3
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==1.10.11
    - regex==2023.6.3
    - sentry-sdk==1.27.1
    - setproctitle==1.3.2
    - smmap==5.0.0
    - tokenizers==0.13.3
    - transformers==4.30.2
    - urllib3==1.26.16
    - wandb==0.15.5
