channels:
  - defaults
  - conda-forge
dependencies:
  - backoff
  - cartopy
  - click
  - conda-build
  - cloudpickle
  - crcmod
  - dask>=2.3
  - fsspec
  - f90nml
  - black=19.10b0
  - isort
  - flake8=3.7.9
  - gcsfs==0.6.0  # 0.6.1 changes filesystem.ls (errors when no files / doesn't exist)
  - google-cloud-storage
  - h5netcdf
  - h5py>=2.10
  - hypothesis
  - pandas=1.0.1
  - intake
  - intake-xarray
  - metpy
  - netcdf4>=1.4
  - numba
  - numpy
  - partd
  - pooch==1.1.1
  - pyyaml==5.3
  - pytest
  - pytest-mpl
  - python-kubernetes
  - scikit-image
  - scikit-learn
  - toolz
  - xarray>=0.14
  - jupyterlab
  - pip
  - xgcm=0.2
  - jupyterlab
  - apache-beam=2.18
  - matplotlib=3.1
  - pyquery>=1.4.0
  - python=3.7
  - holoviews
  - bokeh>=2.0
  - backoff
  - pip
  - pip:
    - zarr>=2.4
    - poetry
    - gsutil
    - nc-time-axis>=1.2.0
    - gitpython
    - bump2version>=0.5.11
    - yq
    - pytest-regtest
