base_version: v0.5
field_table: gs://vcm-fv3config/config/field_table/TKE-EDMF/v1.0/field_table
initial_conditions:
  base_url: gs://vcm-ml-intermediate/2021-08-06-PIRE-c48-restarts-post-spinup
  timestep: "20200119.000000"
scikit_learn:
  use_mse_conserving_humidity_limiter: false
prephysics:
  -
    diagnostic_ml: false
    model:
      - gs://vcm-ml-experiments/n2f-pire-stable-ml/2022-05-24/radiative-fluxes-mae-lat-input-seed-0/trained_models/radiative_fluxes
    output_standard_names:
      override_for_time_adjusted_total_sky_net_shortwave_flux_at_surface: net_shortwave_sfc_flux_via_transmissivity
      override_for_time_adjusted_total_sky_downward_shortwave_flux_at_surface: downward_shortwave_sfc_flux_via_transmissivity
  -
    dataset_key: gs://vcm-ml-intermediate/2021-08-03-PIRE-c48-diags-post-spinup/sst-time-centered.zarr
    variables:
      - ocean_surface_temperature
    reference_initial_time: "20200118.013000"
    reference_frequency_seconds: 10800
  -
    dataset_key: gs://vcm-ml-intermediate/2021-08-03-PIRE-c48-diags-post-spinup/slmsk-seaice-reference.zarr
    variables:
      - land_sea_mask
      - sea_ice_thickness
      - ice_fraction_over_open_water
    reference_initial_time: "20200119.000000"
    reference_frequency_seconds: 604800
namelist:
  atmos_model_nml:
    fhmax: 10240  # max hours of simulation (over all segments) for which fortran physics diags are saved
  namsfc:
    # these flags make the coarse run use the GRIB data for snoalb and vegetation
    # if not included, it will use the restart data (which may differ from GRIB file)
    fabss: 0
    fabsl: 0
    fvmnl: 0
    fvmns: 0
    fvmxl: 0
    fvmxs: 0
  coupler_nml:
    days: 10
    hours: 0
    minutes: 0
    seconds: 0
  diag_manager_nml:
    flush_nc_files: true
  fv_core_nml:
    do_sat_adj: true
    layout:
     - 2
     - 2
  gfdl_cloud_microphysics_nml:
    mp_time: 150.0
    fast_sat_adj: true
  gfs_physics_nml:
    fhlwr: 1800.0
    fhswr: 1800.0
    hybedmf: false
    satmedmf: true
    xkzm_h: 2.0
    override_surface_radiative_fluxes: true
fortran_diagnostics:
- name: sfc_dt_atmos.zarr
  chunks:
    time: 80
  times:
    frequency: 10800
    kind: interval
  variables:
  - {module_name: dynamics, field_name: grid_lont, output_name: lon}
  - {module_name: dynamics, field_name: grid_latt, output_name: lat}
  - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
  - {module_name: dynamics, field_name: grid_lat, output_name: latb}
  - {module_name: dynamics, field_name: area, output_name: area}
  - {module_name: gfs_phys, field_name: dusfci, output_name: uflx}
  - {module_name: gfs_phys, field_name: dvsfci, output_name: vflx}
  - {module_name: gfs_phys, field_name: cnvprcpb_ave, output_name: CPRATsfc}
  - {module_name: gfs_phys, field_name: totprcpb_ave, output_name: PRATEsfc}
  - {module_name: gfs_phys, field_name: toticeb_ave, output_name: ICEsfc}
  - {module_name: gfs_phys, field_name: totsnwb_ave, output_name: SNOWsfc}
  - {module_name: gfs_phys, field_name: totgrpb_ave, output_name: GRAUPELsfc}
  - {module_name: gfs_phys, field_name: DSWRF, output_name: DSWRFsfc}
  - {module_name: gfs_phys, field_name: DSWRF_from_rrtmg, output_name: DSWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: USWRF, output_name: USWRFsfc}
  - {module_name: gfs_phys, field_name: USWRF_from_rrtmg, output_name: USWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: DSWRFtoa, output_name: DSWRFtoa}
  - {module_name: gfs_phys, field_name: USWRFtoa, output_name: USWRFtoa}
  - {module_name: gfs_phys, field_name: ULWRFtoa, output_name: ULWRFtoa}
  - {module_name: gfs_phys, field_name: ULWRF, output_name: ULWRFsfc}
  - {module_name: gfs_phys, field_name: DLWRF, output_name: DLWRFsfc}
  - {module_name: gfs_phys, field_name: DLWRF_from_rrtmg, output_name: DLWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: lhtfl_ave, output_name: LHTFLsfc}
  - {module_name: gfs_phys, field_name: shtfl_ave, output_name: SHTFLsfc}
  - {module_name: gfs_phys, field_name: hpbl, output_name: HPBLsfc}
  - {module_name: gfs_sfc, field_name: fice, output_name: ICECsfc}
  - {module_name: gfs_sfc, field_name: SLMSKsfc, output_name: SLMSKsfc}
  - {module_name: gfs_sfc, field_name: q2m, output_name: SPFH2m}
  - {module_name: gfs_sfc, field_name: t2m, output_name: TMP2m}
  - {module_name: gfs_sfc, field_name: tsfc, output_name: TMPsfc}
  - {module_name: gfs_phys, field_name: dpt2m, output_name: DPT2m}
  - {module_name: gfs_phys, field_name: u10m, output_name: UGRD10m}
  - {module_name: gfs_phys, field_name: v10m, output_name: VGRD10m}
  - {module_name: gfs_phys, field_name: tmpmax2m, output_name: TMAX2m}
  - {module_name: gfs_phys, field_name: wind10mmax, output_name: MAXWIND10m}
  - {module_name: gfs_phys, field_name: soilm, output_name: SOILM}
  - {module_name: gfs_sfc, field_name: SOILT1, output_name: SOILT1}
  - {module_name: gfs_sfc, field_name: SOILT2, output_name: SOILT2}
  - {module_name: gfs_sfc, field_name: SOILT3, output_name: SOILT3}
  - {module_name: gfs_sfc, field_name: SOILT4, output_name: SOILT4}
- name: atmos_dt_atmos.zarr
  chunks:
    time: 80
  times:
    frequency: 10800
    kind: interval
  variables:
  - {module_name: dynamics, field_name: grid_lont, output_name: lon}
  - {module_name: dynamics, field_name: grid_latt, output_name: lat}
  - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
  - {module_name: dynamics, field_name: grid_lat, output_name: latb}
  - {module_name: dynamics, field_name: area, output_name: area}
  - {module_name: dynamics, field_name: us, output_name: UGRDlowest}
  - {module_name: dynamics, field_name: u850, output_name: UGRD850}
  - {module_name: dynamics, field_name: u500, output_name: UGRD500}
  - {module_name: dynamics, field_name: u200, output_name: UGRD200}
  - {module_name: dynamics, field_name: u50, output_name: UGRD50}
  - {module_name: dynamics, field_name: vs, output_name: VGRDlowest}
  - {module_name: dynamics, field_name: v850, output_name: VGRD850}
  - {module_name: dynamics, field_name: v500, output_name: VGRD500}
  - {module_name: dynamics, field_name: v200, output_name: VGRD200}
  - {module_name: dynamics, field_name: v50, output_name: VGRD50}
  - {module_name: dynamics, field_name: tm, output_name: TMP500_300}
  - {module_name: dynamics, field_name: tb, output_name: TMPlowest}
  - {module_name: dynamics, field_name: t850, output_name: TMP850}
  - {module_name: dynamics, field_name: t500, output_name: TMP500}
  - {module_name: dynamics, field_name: t200, output_name: TMP200}
  - {module_name: dynamics, field_name: w850, output_name: w850}
  - {module_name: dynamics, field_name: w500, output_name: w500}
  - {module_name: dynamics, field_name: w200, output_name: w200}
  - {module_name: dynamics, field_name: w50, output_name: w50}
  - {module_name: dynamics, field_name: vort850, output_name: VORT850}
  - {module_name: dynamics, field_name: vort500, output_name: VORT500}
  - {module_name: dynamics, field_name: vort200, output_name: VORT200}
  - {module_name: dynamics, field_name: z850, output_name: h850}
  - {module_name: dynamics, field_name: z500, output_name: h500}
  - {module_name: dynamics, field_name: z200, output_name: h200}
  - {module_name: dynamics, field_name: rh1000, output_name: RH1000}
  - {module_name: dynamics, field_name: rh925, output_name: RH925}
  - {module_name: dynamics, field_name: rh850, output_name: RH850}
  - {module_name: dynamics, field_name: rh700, output_name: RH700}
  - {module_name: dynamics, field_name: rh500, output_name: RH500}
  - {module_name: dynamics, field_name: q1000, output_name: q1000}
  - {module_name: dynamics, field_name: q925, output_name: q925}
  - {module_name: dynamics, field_name: q850, output_name: q850}
  - {module_name: dynamics, field_name: q700, output_name: q700}
  - {module_name: dynamics, field_name: q500, output_name: q500}
  - {module_name: dynamics, field_name: slp, output_name: PRMSL}
  - {module_name: dynamics, field_name: ps, output_name: PRESsfc}
  - {module_name: dynamics, field_name: tq, output_name: PWAT}
  - {module_name: dynamics, field_name: lw, output_name: VIL}
  - {module_name: dynamics, field_name: iw, output_name: iw}
  - {module_name: dynamics, field_name: ke, output_name: kinetic_energy}
  - {module_name: dynamics, field_name: te, output_name: total_energy}
diagnostics:
- name: diags.zarr
  chunks:
    time: 80
  times:
    frequency: 10800
    kind: interval
  variables:
  - net_moistening_due_to_machine_learning
  - column_heating_due_to_machine_learning
  - total_precipitation_rate
  - water_vapor_path
  - physics_precip
  - column_integrated_dQu_stress
  - column_integrated_dQv_stress
  - is_novelty
  - novelty_score
- name: diags_3d.zarr
  chunks:
    time: 10
  times:
    frequency: 21600
    kind: interval
  variables:
  - dQ1
  - dQ2
  - dQu
  - dQv
  - tendency_of_air_temperature_due_to_fv3_physics
  - tendency_of_specific_humidity_due_to_fv3_physics
  - tendency_of_eastward_wind_due_to_fv3_physics
  - tendency_of_northward_wind_due_to_fv3_physics
- name: state_after_timestep.zarr
  chunks:
    time: 10
  times:
    frequency: 21600
    kind: interval
  variables:
  - eastward_wind
  - northward_wind
  - vertical_wind
  - air_temperature
  - specific_humidity
  - pressure_thickness_of_atmospheric_layer
  - vertical_thickness_of_atmospheric_layer
  - land_sea_mask
  - surface_temperature
  - surface_geopotential
  - sensible_heat_flux
  - latent_heat_flux
  - total_precipitation
  - surface_precipitation_rate
  - total_soil_moisture
  - total_sky_downward_shortwave_flux_at_surface
  - total_sky_upward_shortwave_flux_at_surface
  - total_sky_downward_longwave_flux_at_surface
  - total_sky_upward_longwave_flux_at_surface
  - total_sky_downward_shortwave_flux_at_top_of_atmosphere
  - total_sky_upward_shortwave_flux_at_top_of_atmosphere
  - total_sky_upward_longwave_flux_at_top_of_atmosphere
  - clear_sky_downward_shortwave_flux_at_surface
  - clear_sky_upward_shortwave_flux_at_surface
  - clear_sky_downward_longwave_flux_at_surface
  - clear_sky_upward_longwave_flux_at_surface
  - clear_sky_upward_shortwave_flux_at_top_of_atmosphere
  - clear_sky_upward_longwave_flux_at_top_of_atmosphere
  - latitude
  - longitude
  - cloud_water_mixing_ratio
  - cloud_ice_mixing_ratio
  - rain_mixing_ratio
  - snow_mixing_ratio
  - graupel_mixing_ratio
  - surface_diffused_shortwave_albedo
