resources:
- prognostic_run_diags.yaml
- prognostic-run.yaml
- training.yaml
- run-fv3gfs.yaml
- offline-diags.yaml
- train-diags-prog.yaml
- cubed-to-latlon.yaml
configurations:
- image-transformerconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
