coarse_nudged_path: gs://vcm-ml-experiments/cloud-ml/2023-06-06/cloud-ml-prognostic-run-nudge-to-fine-baseline/fv3gfs_run
coarse_state_zarr: state_pre_radiation.zarr
fine_keys:
  - 10day_c48_PIRE_ccnorm_gfsphysics_15min_may2023
  - 10day_c48_PIRE_ccnorm_restarts_as_zarr_may2023
fine_rename:
  liq_wat: cloud_water_mixing_ratio
  ice_wat: cloud_ice_mixing_ratio
  cld_amt: cloud_amount
coarse_rename:
  air_temperature_pre_radiation: air_temperature
  specific_humidity_pre_radiation: specific_humidity
  pressure_thickness_of_atmospheric_layer_pre_radiation: pressure_thickness_of_atmospheric_layer
  cloud_ice_mixing_ratio_pre_radiation: cloud_ice_mixing_ratio_coarse
output_path: gs://vcm-ml-experiments/cloud-ml/2023-06-07/cloud-ml-training-data.zarr