[tool.poetry]
name = "gallery"
version = "0.1.0"
description = ""
authors = ["Oliver Watt-Meyer <oliwm@vulcan.com>"]

[tool.poetry.dependencies]
matplotlib = "^3.1"
pandas = "^1.0"
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
