[tool.poetry]
name = "runtime"
version = "0.1.0"
description = ""
authors = ["Noah D. Brenowitz <nbren12@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
f90nml = "^1.1.2"
sklearn = "^0.0"
numpy = "^1.18.2"
xarray = "^0.15.1"
zarr = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
